//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Resources;
using System.Globalization;

#nullable enable

namespace ScreenNap.Resources;

internal static class Strings
{
    private static ResourceManager? s_resourceManager;

    private static ResourceManager ResourceManager =>
        s_resourceManager ??= new ResourceManager("ScreenNap.Resources.Strings",
            typeof(Strings).Assembly);

    internal static string MenuReleaseAll =>
        ResourceManager.GetString("MenuReleaseAll", CultureInfo.CurrentUICulture) ?? "Release All";

    internal static string MenuExit =>
        ResourceManager.GetString("MenuExit", CultureInfo.CurrentUICulture) ?? "Exit";

    internal static string MenuPrimary =>
        ResourceManager.GetString("MenuPrimary", CultureInfo.CurrentUICulture) ?? "[Primary]";

    internal static string MenuActive =>
        ResourceManager.GetString("MenuActive", CultureInfo.CurrentUICulture) ?? "(Active)";

    internal static string TooltipNormal =>
        ResourceManager.GetString("TooltipNormal", CultureInfo.CurrentUICulture) ?? "ScreenNap";

    internal static string TooltipActive =>
        ResourceManager.GetString("TooltipActive", CultureInfo.CurrentUICulture) ?? "ScreenNap ({0} active)";

    internal static string NotifyAlreadyRunning =>
        ResourceManager.GetString("NotifyAlreadyRunning", CultureInfo.CurrentUICulture) ?? "ScreenNap is already running.";

    internal static string NotifyTitle =>
        ResourceManager.GetString("NotifyTitle", CultureInfo.CurrentUICulture) ?? "ScreenNap";
}
